openapi: 3.0.0
info:
  title: Auth System
  description: An authentication app created using express.js and mongodb
  version: 1.0.1
  contact:
    name: API Support
    email: shubhampurwar35@gmail.com

servers:
  - url: https://localhost:4000/api/v1
    description: Development server
  - url:
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: token

  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNo:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    Response:
      type: object
      properties:
        success:
          type: boolean
          default: true
        message:
          type: string

    Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string

  responses:
    UnauthorizedError:
      description: Authorization information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: User not found
      content:
        application/json:
          schema:
            $ref: '#components/schemas/Error'

    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#components/schemas/Error'

paths:
  /signup:
    post:
      description: Allows user to signup
      requestBody:
        description: A JSON object containing values provided by user to signup
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                phoneNo:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: Signup success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /login:
    get:
      description: Allows user to login
      requestBody:
        description: A JSON object containing values provided by user to login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: User email or phone no.
                password:
                  type: string
      responses:
        '200':
          description: >
            Login success
            A JWT token is returned in a cookie named 'token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          headers:
            Set-Cookie:
              schema:
                type: string
        '401':
          $ref: '#/components/schemas/UnauthorizedError'
        '404':
          $ref: '#/components/schemas/NotFoundError'
        '500':
          $ref: '#/components/schemas/UnexpectedError'

  /logout:
    get:
      description: Allows user to logout
      responses:
        '200':
          description: >
            Logout success
            Cookie value is set to null upon successful logout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          headers:
            Set-Cookie:
              schema:
                type: string
        '500':
          $ref: '#/components/schemas/UnexpectedError'
