openapi: 3.0.0
info:
  title: Auth System
  description: An authentication app created using express.js and mongodb
  version: 1.0.1
  contact:
    name: API Support
    email: shubhampurwar35@gmail.com

servers:
  - url: https://localhost:4000/api/v1
    description: Development server
  - url:
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: token

  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNo:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    Response:
      type: object
      properties:
        success:
          type: boolean
          default: true
        message:
          type: string

    Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string

  responses:
    UnauthorizedError:
      description: Client unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#components/schemas/Error'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#components/schemas/Error'

paths:
  /signup:
    post:
      description: Allows user to signup
      requestBody:
        description: A JSON object containing values provided by user to signup
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                phoneNo:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
