openapi: 3.0.0
info:
  title: Auth System
  description: An authentication app created using express.js and mongodb
  version: 1.0.1
  contact:
    name: API Support
    email: shubhampurwar35@gmail.com

servers:
  - url: http://localhost:4000/api/v1
    description: Development server
  - url:
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: token

  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNo:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    Response:
      type: object
      properties:
        success:
          type: boolean
          default: true
        message:
          type: string

    Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string

  responses:
    UnauthorizedError:
      description: Authorization information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: User not found
      content:
        application/json:
          schema:
            $ref: '#components/schemas/Error'

    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#components/schemas/Error'

paths:
  /auth/signup:
    post:
      tags:
        - Authentication routes
      description: Allows user to signup
      requestBody:
        description: A JSON object containing values provided by user to signup
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                phoneNo:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: Signup success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/login:
    post:
      tags:
        - Authentication routes
      description: Allows user to login
      requestBody:
        description: A JSON object containing values provided by user to login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: User email or phone no.
                password:
                  type: string
      responses:
        '200':
          description: >
            Login success
            A JWT token is returned in a cookie named 'token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          headers:
            Set-Cookie:
              schema:
                type: string
                description: Cookie information
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/logout:
    get:
      tags:
        - Authentication routes
      description: Allows user to logout
      responses:
        '200':
          description: >
            Logout success
            Cookie value is set to null upon successful logout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          headers:
            Set-Cookie:
              schema:
                type: string
                description: Cookie information
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/password/forgot:
    put:
      tags:
        - Authentication routes
      description: Sends reset password mail to the user
      requestBody:
        description: A JSON object containing user email
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Mail with link to reset password is successfully sent to the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/password/reset/{resetPasswordToken}:
    put:
      tags:
        - Authentication routes
      description: Allows user to reset password
      parameters:
        - name: resetPasswordToken
          in: path
          description: Token to reset password
          required: true
          schema:
            type: string
            format: hex
      requestBody:
        description: A JSON object containing password and confirmPassword
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: Password reset success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/profile:
    get:
      tags:
        - Authentication routes
      description: Allows user to access profile
      security:
        - BearerAuth
        - CookieAuth
      responses:
        '200':
          description: Profile successfully fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/password/change:
    put:
      tags:
        - Authentication routes
      description: Allows user to change password
      security:
        - BearerAuth
        - CookieAuth
      requestBody:
        description: A JSON object containing currentPassword and newPassword
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        '201':
          description: Password successfully changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'

  /auth/profile/delete:
    delete:
      tags:
        - Authentication routes
      description: Allows user to delete profile
      security:
        - BearerAuth
        - CookieAuth
      requestBody:
        description: A JSON object containing password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password: string
      responses:
        '200':
          description: Profile successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
